services:
  mongodb:
    build:
      context: './mongodb'
      dockerfile: 'Dockerfile'
    container_name: 'contiene_mongo'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    volumes:
      - './data/db:/data/db'
      - './mongodb/productos.json:/docker-entrypoint-initdb.d/productos.json'  # Monta el archivo JSON como un volumen

  mysql:
    image: 'mysql:latest'
    container_name: 'contiene_mysql'
    environment:
      - 'MYSQL_DATABASE=integradora'
      - 'MYSQL_ROOT_PASSWORD=admin'
    ports:
      - '3306:3306'

  tomcat:
    container_name: 'contiene_tomcat'
    image: 'tomcat:latest'
    ports:
      - "8080:8080"
    volumes:
      - './build/libs/tienda.war:/usr/local/tomcat/webapps/tienda.war'

    node:
      container_name: 'contiene_node'
      build:
        context: './node' # Carpeta donde se encuentra el Dockerfile
      ports:
        - "8081:8081"
      volumes:
        - '.:/app'
      working_dir: '/app'