const listaProductos = [
    {
        modelo: "clase b",
        marca: "MERCEDES-BENZ",
        categoria: "Familiar",
        precio: 120.52,
        cantidad: 50,
    },
    {
        modelo: "serie 1",
        marca: "BMW",
        categoria: "Compacto",
        precio: 140.71,
        cantidad: 50,
    },
    {
        modelo: "qashqai",
        marca: "NISSAN",
        categoria: "familiar",
        precio: 194.16,
        cantidad: 50,
    },
    {
        modelo: "gulietta",
        marca: "ALFA ROMEO",
        categoria: "Deportivo",
        precio: 167.47,
        cantidad: 50,
    },
    {
        modelo: "e-tron",
        marca: "AUDI",
        categoria: "Lujo",
        precio: 373.34,
        cantidad: 50,
    },
    {
        modelo: "clase s",
        marca: "MERCEDES-BENZ",
        categoria: "Lujo",
        precio: 457.72,
        cantidad: 50,
    },
    {
        modelo: "Focus",
        marca: "Ford",
        categoria: "Compacto",
        precio: 155.99,
        cantidad: 30,
    },
    {
        modelo: "Civic",
        marca: "Honda",
        categoria: "Compacto",
        precio: 170.25,
        cantidad: 40,
    },
    {
        modelo: "Corolla",
        marca: "Toyota",
        categoria: "Compacto",
        precio: 180.50,
        cantidad: 25,
    },
    {
        modelo: "Camry",
        marca: "Toyota",
        categoria: "Sedan",
        precio: 210.75,
        cantidad: 35,
    },
    {
        modelo: "Accord",
        marca: "Honda",
        categoria: "Sedan",
        precio: 200.00,
        cantidad: 45,
    },
    {
        modelo: "X5",
        marca: "BMW",
        categoria: "SUV",
        precio: 350.80,
        cantidad: 20,
    },
    {
        modelo: "Tucson",
        marca: "Hyundai",
        categoria: "SUV",
        precio: 190.30,
        cantidad: 30,
    },
    {
        modelo: "CR-V",
        marca: "Honda",
        categoria: "SUV",
        precio: 220.45,
        cantidad: 35,
    },
    {
        modelo: "CX-5",
        marca: "Mazda",
        categoria: "SUV",
        precio: 205.60,
        cantidad: 25,
    },
    {
        modelo: "Model S",
        marca: "Tesla",
        categoria: "Electrico",
        precio: 500.00,
        cantidad: 15,
    }
];